---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install firewalld
      package:
        name:
          - firewalld
        state: present

    - name: Start firewalld
      command: systemctl start firewalld

  roles:
    - role: gluestix.teleport-client
