---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install firewalld
      package:
        name:
          - firewalld
        state: present

  roles:
    - role: gluestix.teleport
