---
# This is a basic workflow to help you get started with Actions

name: KICS

'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "30 4 * * 4"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: run kics Scan
        uses: Checkmarx/kics-github-action@v1.5
        with:
          # scanning directory: ./tasks/
          path: 'tasks'
          output_path: myResults/
      # Display the results in json format
      - name: display kics results
        run: |
          cat myResults/results.json
